[package]
authors = ["Rafael Varago <varago.rafael@gmail.com>"]
description = "A small and experimental library with a type-level representation of booleans with companion connectives for compile-time sort-of fun"
edition = "2018"
name = "rustollens"
version = "0.1.0"
